repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.4.0
  #   hooks:
  #     - id: check-added-large-files
  # - repo: https://github.com/ambv/black
  #   rev: 24.4.2
  #   hooks:
  #     - id: black
  # - repo: https://github.com/timothycrosley/isort
  #   rev: '5.13.2'
  #   hooks:
  #     - id: isort
  #       additional_dependencies:
  #         - toml
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --max-complexity=10]
